### ISSUE TITLE
MiWIFI loses connection

### ISSUE THREAD

**Issue by vitich** [eisaev/r2350#1]
First of all - thanks a lot! 
I did everything according to your documentation and everything worked out. But there is a small minor problem - since I set China in the settings, the application first detects the router, connects to it, and then loses connection with it forever. I tried all applications and reccomendations from 4pda but still without success.

**Comment by eisaev** [comment]
This is a known issue. I don't use the app and also rely on information from other community members (mostly from the same 4pda). I still do not know what exactly this application gives, which is not available in the web interface. The only thing I needed from it was to control the led indication, but I implemented it in a modified rootfs.
I see further development of modifications in cleaning the firmware from the manufacturer's garbage, but this will definitely kill the work with the native application. In this regard, I do not yet see any prospects for restoring the functionality of the application with the modified firmware. If the community has some universal solution or at least a suggestion on how to keep it working, but with the option of turning it off, then I am ready to discuss it.

**Comment by MarioK239** [comment]
With the mi wifi app you can turn on the guest network, control the firewall (suspicious device notification etc.), wifi optimization, scheduled router config backups, wifi schedule, network optimization, wps connection and qos control (game mode, video mode etc.). I think that's all.

**Comment by eisaev** [comment]
@MarioK239, thanks! This is very useful information. Most likely, I have not encountered any of this because I use this router as an access point.

**Comment by homifatal** [comment]
I have mi wifi app on iOS up and running by doing this:

1. set the location of router to Australia
2. change the location of the app to Australia (if you location is set to australia just choose another location and put it back to AUS)
3. clear cache of the app
4. pair the router with the app

**Comment by MarioK239** [comment]
Hi! This might help: https://forum.openwrt.org/t/support-aiot-ac2350-xiaomi/70451/173?u=mariok239

**Comment by eisaev** [comment]
Fixed mod7 (a7575a36ebcfdda9d0359cafc33b0213cb2bd608)
