### ISSUE TITLE
Can't acces to router

### ISSUE THREAD

**Issue by xmochyx** [eisaev/r2350#12]
Hi, maybe I did a big mistake

I followed the steps in this tutorial to patch art (because I have the black/global version)
I want use the router with mi wifi app, finally I changed to RAE china to login, and don't work.
I tried access login to router with url and now, don't load, always charging.
My question is: what happens if I press the reset button? I need do the steps again or nothing?

Thanks for the help

**Comment by hartkopp** [comment]
> Hi, maybe I did a big mistake
> 
> I followed the steps in this tutorial to patch art (because I have the black/global version) I want use the router with mi wifi app, 

When you install OpenWRT following this documantation, you have an OpenWRT router afterwards.
The MI WIFI App will not work with an OpenWRT Router.
 
>finally I changed to RAE china to login, and don't work. I tried access login to router with url and now, don't load, always charging. My question is: what happens if I press the reset button? I need do the steps again or nothing?

When you boot your router, which Firmware is installed? Still the China SW or already OpenWRT?

**Comment by xmochyx** [comment]
Thanks for the answer

I have the China SW,  the file called firmware.7.mod.bin 
Not the OpenWRT.
If I press the reset button I need Patch Bdata partition and art partition? Or can I brick the router? Is the fear that I have

**Comment by hartkopp** [comment]
I do not think anything is broken with your router.
You just need to follow the steps given in the README.md.

When I was installing OpenWRT the first time I missed the step of changing the ART partition which made my router run with very low wifi power.

So I started once again from the beginning with https://github.com/eisaev/r2350#debricking-lite process.
That just burned some lifetime but I learned something new ;-)

Summary: Just start from the top. After flashing the firmware.7.mod.bin you need to ssh to the router again and do the BDATA and ART modifications before installing the OpenWRT sysimage.

**Comment by xmochyx** [comment]
Thanks a lot for the help.
i will try it when i have some time.

And yes, it's good learn something everyday 😄

**Comment by Patrick761** [comment]
Hi, I'm trying to flash the router with OpenWRT. I'm just wondering on why can't we just flash the firmware directly with OpenWRT using the firmware updater that is built in the Mi Wifi ?

**Comment by hartkopp** [comment]
> Hi, I'm trying to flash the router with OpenWRT. I'm just wondering on why can't we just flash the firmware directly with OpenWRT using the firmware updater that is built in the Mi Wifi ? Also, is it ok if I'm using Bash to execute the linux scripts on Windows?

Can you please open a new issue for that question and delete this post? Thanks.
