### ISSUE TITLE
Unable to SSH - missing S/N

### ISSUE THREAD

**Issue by m4chin3** [eisaev/r2350#13]
Hello. I have been using the method to obtain the SSH access via the methods described in this repository in the past, and everything was working well for me. However, due to some glitches in the 2.4GHz connections, I rolled the router back to the INT version (3.0.36 version).

After OpenWRT became officially supported, I've decided to give it another try. I load up the web interface, pick up the **stock** value, send the http request with the stock to enable ssh and generate keys, wait for a few minutes to make sure the keys were generated before proceeding to calculate the ssh password according to my S/N.

But lo and behold - I have no serial number present in the router interface! The server just doesn't render anything there!

So, naturally, I've tried using the SN from the label found on the bottom of the device to generate an SSH password (and I'm sure this password is the same as it was before, so the serial number from the label is the same as the one I used to have in the router web interface).

Finally, when trying to SSH to the device as root, i keep getting: ```Permission denied, please try again.```

I have also tried re-flashing 3.0.36, then back to 1.3.8 using all combinations of

- resetting settings while flashing from 3.0.36 to 1.3.8
- doing reflashes with and without WAN/internet connected
- doing factory resets both on 3.0.36 and 1.3.8
- tried ssh both via local router address (192.168.31.1) and thru WAN (the IP assigned by external router via DHCP, in cases when WAN/internet was connected)

After almost 4 hours, I am still in a situation where:
- I have no serial number rendered in the web interface, regardless of the current firmware version
- Any attempts to SSH using the password calculated from the serial number from the label on the bottom of the router fail with permission denied
- I am positive that the calculated password used to work in the past since I've found backup txt file where I was writing down the commands used

Any ideas? Or I am locked out of my router for good?

**Comment by m4chin3** [comment]
Haven't tried it yet, but you do have a point. I will report back here once I do this process (need to set up a Windows machine first tho). Thank you for the suggestion!

**Comment by hartkopp** [comment]
When you are experienced with TFTP servers on Linux you might also use a Linux system for that. But I had a Windows system at hand so I followed the description ... (lazy mode) :-D

**Comment by m4chin3** [comment]
Hi, I just got some time to try this out and it didn't work. I've tried flashing both stock china and stock INTL - and flashing finishes successfully; but yet again - it's as if I don't have the serial number somehow, and am thus unable to obtain SSH access.

The router, other than that, actually works ok-ish (I see that wifi connections are less stable than they used to be, occasional breaks in wifi, using the router as a wired repeater).

Any ideas how to get my SN back so I could get the SSH access again?

**Comment by hartkopp** [comment]
Hm, just to make sure:
When you connect to http://192.168.31.1 on a factory-reset system via Ethernet you get a configuration HMI screen, right?

**Comment by m4chin3** [comment]
Yeah, the router works seemingly fine other than the fact I can't obtain ssh access. I normally go pass the initial configuration and set it up just fine. The only real difference is that I don't have the serial number rendered on the router web page; I've tried using the original serial number from the label on the router to generate the password for ssh, but I get a permission denied trying to ssh (when I go through the whole process to obtain ssh, with the CN version of firmware).

Right now, just for the english language in the interface, I've moved to the INTL stock firmware version. Here's an image of the portion that should render the SN: https://i.imgur.com/w0ZapXX.png (it's exactly the same on CN version too).

It literally doesn't render anything, the ```<td>``` element that should hold the SN value is empty.

**Comment by hartkopp** [comment]
I checked out my backup files made from the original router with this mtd layout:
```
dev:    size   erasesize  name
mtd0: 00030000 00010000 "Bootloader"
mtd1: 00010000 00010000 "Nvram"
mtd2: 00010000 00010000 "Bdata"
mtd3: 00010000 00010000 "crash"
mtd4: 00010000 00010000 "art"
mtd5: 00020000 00010000 "cfg_bak"
mtd6: 00170000 00010000 "overlay"
mtd7: 00e00000 00010000 "firmware"
mtd8: 00250000 00010000 "kernel"
mtd9: 00bb0000 00010000 "rootfs"
mtd10: 00850000 00010000 "rootfs_data"
```

My serial number on the router is something with `E0QM` so I grep'd the mtd-files for that:
```
$ grep E0QM *
grep: mtd1: binary file matches
grep: mtd2: binary file matches
```

I used `GHex` to look into the binary mtd files:

While `mtd1`  looks like an uboot environment containing entries like `bootdelay=2` the `mtd2` partition contains things like the country code, model, miot_key, default wlan_ssids and more.

Both(!) partitions contain the serial number in a tag like: `SN=12345/E0QM67890` (not my real numbers)

I would assume the system retrieves the SN from either of these partitions.

Did you make a mtd backup that you could probably write back?
Maybe you would need to attach the serial console to enter the uboot at system startup - and check/set the SN there.

**Comment by m4chin3** [comment]
Thanks for this update! I've found my ```ALL.backup``` created with ``` if=/dev/mtd0 of=/tmp/ALL.backup``` back when I was going through the process for the first time. It does have the SN inside, while the fw files (```miwifi_r2350_firmware_0cc61_1.3.8.bin``` and ```miwifi_r2350_firmware_bd55f_3.0.36_INT.bin```) do not have the serial inside (the entry "SN=" exists, but the following bytes don't contain the SN).

The trouble right now is - I can't get the backup I initially had made back to the router, at least not via ssh/scp.

PS: an interesting thing I've also noticed - I did a log dump from the web interface back when I first had flashed the router - and it also contains populated ```SN=``` entries, in the ```bdata.txt``` and ```nvram.txt``` files that router dumps when you request logs. However, I've done this today also - and there are no ```SN=``` entries in the fresh log dump. I guess this matches what you had found in your mtd backups.

So, considering everything - any advice on how I could possibly proceed? (perhaps any resources on attaching serial console to this router?)

**Comment by hartkopp** [comment]
> Thanks for this update! I've found my `ALL.backup` created with ` if=/dev/mtd0 of=/tmp/ALL.backup` back when I was going through the process for the first time. It does have the SN inside, while the fw files (`miwifi_r2350_firmware_0cc61_1.3.8.bin` and `miwifi_r2350_firmware_bd55f_3.0.36_INT.bin`) do not have the serial inside (the entry "SN=" exists, but the following bytes don't contain the SN).

Yes, I've seen that too.

> The trouble right now is - I can't get the backup I initially had made back to the router, at least not via ssh/scp.

:-(

> PS: an interesting thing I've also noticed - I did a log dump from the web interface back when I first had flashed the router - and it also contains populated `SN=` entries, in the `bdata.txt` and `nvram.txt` files that router dumps when you request logs. However, I've done this today also - and there are no `SN=` entries in the fresh log dump. I guess this matches what you had found in your mtd backups.

Was this a dump process with the stock firmware? Can you probably restore this backup of  `bdata.txt` and `nvram.txt` files with the stock firmware??
These files are likely just copied into `mtd1` and `mtd2`.

> So, considering everything - any advice on how I could possibly proceed? (perhaps any resources on attaching serial console to this router?)
> 
> EDIT: alternatively to serial console approach - do you think it would be possible to edit the existing stock firmware files to insert my own SN via hex editor and reflash? I have no idea on the file formats in use, whether or not the router does some checksum checking when flashing etc.

Yes. In your position I would start to solder the serial console pins (see picture at https://openwrt.org/toh/xiaomi/aiot_router_ac2350) and see what I could do with the uboot console. E.g. uploading patched mtd partitions via tftp or directly echo/cat the ASCII texts into the mtd-devices (after unlocking them).

I can send you my two mtd1/mtd2 files (64kByte each) with all my data and my real serial number if you want to take a look into it. Will not upload it here but you can send an private e-mail to me (see my profile) and I'll send them back to you.

**Comment by hartkopp** [comment]
> All I had to do is calculate the password like this:
> 
> `printf "%s6d2df50a-250f-4a30-a5e6-d44fb0960aa0" | md5 | head -c8`

Haha, excellent! 

In fact when there is no SN the `%s` becomes obsolete too.  So
`printf "6d2df50a-250f-4a30-a5e6-d44fb0960aa0" | md5 | head -c8`
will create the correct password.

> And the calculated password was correct! I have just obtained the SSH access. (perhaps this should be added to the README on this router?)

Good idea!

> I will consider restoring the whole backup now via SSH to see whether or not I'll be able to change the SN back to its original value. And will likely proceed with OpenWRT install later on.

Good luck ;-)

> Thank you for all your help, without your advice I would have never thought of this and would be stuck with my problem still. I guess uboot's gonna have to wait for the next time I am stuck with this :)

Yes, it was interesting for me too. Thanks for the conversation!

Best regards,
Oliver
