### ISSUE TITLE
Flashing using the built in firmware updater? 

### ISSUE THREAD

**Issue by Patrick761** [eisaev/r2350#14]
Hi, I'm trying to flash the router with OpenWRT. I'm just wondering on whether we can flash the firmware directly with OpenWRT using the firmware updater that is built in the Mi Wifi ? Also, is it ok if I'm using Bash to execute the linux scripts on Windows?

**Comment by hartkopp** [comment]
> Hi, I'm trying to flash the router with OpenWRT. I'm just wondering on whether we can flash the firmware directly with OpenWRT using the firmware updater that is built in the Mi Wifi ?

There are more steps to perform the transition from the Mi firmware to OpenWrt than only flashing the firmware partition of the router. E.g. the ART and BDATA partitions need to be modified (see documentation). Once these modifications are done and OpenWrt is working a simple sysupgrade can be performed to upgrade the OpenWrt router.

> Also, is it ok if I'm using Bash to execute the linux scripts on Windows?

The scripts are executed on the router itself. So the putty toolset should work to log into the router and run the scripts.

**Comment by Patrick761** [comment]
I see. Thanks for the explanation!
