### ISSUE TITLE
Obtain SSH access returns inmediately code:0

### ISSUE THREAD

**Issue by mslaats** [eisaev/r2350#2]
I've flashed the CN firmware (miwifi_r2350_firmware_0cc61_1.3.8.bin.7z - 1.3.8 (China)) and after setting up a Wi-Fi password I was able to log in the device.
I've copied the stok value and paste it with in the webbrowser combined with the url from your instructions.
Badly enough the browser showed within a second this response:
{"code":0}

Did I forget to change more in the url or something else?

**Comment by MarioK239** [comment]
If I remember correctly this is what is supposed to happen. After this you need to wait about 1 minute and open windows powershell and type  ssh root@router_ip (replace router_ip with the ip address of the router) . You will get password prompt. Now calculate password as stated in readme and you should have ssh access.

**Comment by eisaev** [comment]
@MarioK239's answer is completely correct.
