### ISSUE TITLE
VPN is not functioning after updating to mod fm

### ISSUE THREAD

**Issue by homifatal** [eisaev/r2350#3]
[2021-04-09--18-17-14.tar.gz](https://github.com/eisaev/r2350/files/6286182/2021-04-09--18-17-14.tar.gz)

I have attached router log for your consideration.

**Comment by eisaev** [comment]
Unfortunately, there is nothing interesting about VPN connections in the logs. I have a suspicion that the issue is related to the use of the Chinese kernel with the international rootfs in mod. @homifatal, if you are ready to test, then I can build a firmware with an international kernel.

**Comment by homifatal** [comment]
Unfortunately I don't have the logs from the stock firmware but i am ready to test the new firmware.

Yes exactly. it connect to the VPN server but the router does not route the traffic through the connection.

**Comment by doalsetlt** [comment]
Faced with the same situation.
I described my situation in 4pda. No one helped.

**Comment by eisaev** [comment]
Please flash the router according to the updated instructions: https://github.com/eisaev/r2350/commit/14a4a718842b8a8ec0b7dd00c2d7826b62566e9b
