### ISSUE TITLE
Can't change to AP mode

### ISSUE THREAD

**Issue by papimigas** [eisaev/r2350#4]
After full-reset and first configuration (wifi, password, etc) I try to change mode to AP and always fail.
The answer is:
"Couldn't use wired repeater"

Then, only after 10 sec hard-reset I can get my router back.
Can you please test this?

**Comment by MarioK239** [comment]
I also noticed that. I might try to switch to stock firmware and see if it works then. With the mod it says that it failed to switch to ap mode and then the router becomes inaccessible and to use it again you need to do a factory reset from the button.

**Comment by eisaev** [comment]
Description updated: https://github.com/eisaev/r2350/commit/eb72aad1ba29e3fee7ceabb86b14482933a5d7aa

**Comment by MarioK239** [comment]
With the new mod firmware which includes an international version of the kernel the wired repeater (access point) mode now works correctly.

**Comment by papimigas** [comment]
Hey, thanks!
Later I detected I have to use other port than WAN, for AP mode.
