### ISSUE TITLE
OpenWrt: image builder/official support

### ISSUE THREAD

**Issue by MariosK239** [eisaev/r2350#5]
Hi! 
I would like to generate custom openwrt images for this router to, for example install sqm, replace ath10k-ct with regular ath10k etc. Would it be possible to provide an image builder version with all the patches and appropriate files for this router? Or, even better, can official openwrt support be added so we can build our own images straight from the latest openwrt source instead of an outdated snapshot?
Thanks!

**Comment by MariosK239** [comment]
Just found the repository: https://github.com/eisaev/openwrt/tree/xiaomi_aiot-ac2350_pr
And here's the pr: https://github.com/openwrt/openwrt/pull/4161

**Comment by Neustradamus** [comment]
Merged commit is:
- https://github.com/openwrt/openwrt/commit/6c148116f778bfd2db88476cee4753b32538eafe
