### ISSUE TITLE
Remove additional services from the mod

### ISSUE THREAD

**Issue by jww-cw** [eisaev/r2350#7]
If possible could you remove some of the vendor based services and crons from the device in you mod?

https://forum.openwrt.org/t/xiaomi-ax3600-int-firmware/74276/214

```
# dont start crap services
for SVC in stat_points statisticsservice \
		datacenter \
		smartcontroller \
		plugincenter plugin_start_script.sh cp_preinstall_plugins.sh; do
	rm -f $FSDIR/etc/rc.d/[SK]*$SVC
done

# prevent stats phone home & auto-update
for f in StatPoints mtd_crash_log logupload.lua otapredownload wanip_check.sh; do > $FSDIR/usr/sbin/$f; done

rm -f $FSDIR/etc/hotplug.d/iface/*wanip_check

sed -i '/start_service(/a return 0' $FSDIR/etc/init.d/messagingagent.sh

# cron jobs are mostly non-OpenWRT stuff
for f in $FSDIR/etc/crontabs/*; do
	sed -i 's/^/#/' $f
done

# as a last-ditch effort, change the *.miwifi.com hostnames to localhost
sed -i 's@\w\+.miwifi.com@localhost@g' $FSDIR/etc/config/miwifi
```

**Comment by eisaev** [comment]
I cannot do this for everyone, as some users use these services. You can do this yourself manually via the ssh console.

**Comment by jww-cw** [comment]
Could you confirm the process you used to patch your mod? Does it use xqrepack?

**Comment by eisaev** [comment]
You don't need to repackage the firmware. These changes can be made on the already installed mod firmware.

**Comment by jww-cw** [comment]
awesome, thank you! I didnt know this was writable.
