### ISSUE TITLE
on router

### ISSUE THREAD

**Issue by MuntadherTY** [eisaev/r2350#8]
hello,
sorry for the stupid question, but what do you mean when u say (on router), like:
Create a backup of all-flash (on router):
`dd if=/dev/mtd0 of=/tmp/ALL.backup`

please I need your help since you installed OpenWRT succwsfully

**Comment by MariosK239** [comment]
It means to execute the command through the routers ssh shell. You first have to get ssh access.

**Comment by MuntadherTY** [comment]
> It means to execute the command through the routers ssh shell. You first have to get ssh access.

thx for your reply but how do i get the access and the routers ssh shell?

**Comment by MariosK239** [comment]
If you want to install openwrt you can follow this guide: https://openwrt.org/toh/xiaomi/aiot_router_ac2350
Otherwise, you have to obtain ssh access using the url and then calculate the password (below the creating backup step). Then connect through ssh: on windows powershell write:    
  ssh root@192.168.31.1   
or use a program like putty to connect.

**Comment by MuntadherTY** [comment]
> If you want to install openwrt you can follow this guide: https://openwrt.org/toh/xiaomi/aiot_router_ac2350
> Otherwise, you have to obtain ssh access using the url and then calculate the password (below the creating backup step). Then connect through ssh: on windows powershell write:
> ssh root@192.168.31.1
> or use a program like putty to connect.

wow man i did <ssh root@192.168.31.1> and worked ur life savor

**Comment by MuntadherTY** [comment]
> If you want to install openwrt you can follow this guide: https://openwrt.org/toh/xiaomi/aiot_router_ac2350
> Otherwise, you have to obtain ssh access using the url and then calculate the password (below the creating backup step). Then connect through ssh: on windows powershell write:
> ssh root@192.168.31.1
> or use a program like putty to connect.

bro can i contact u? can u give me your telegram or any social media cuz i got stuck in network interfaces

**Comment by MariosK239** [comment]
Have you installed openwrt or the stock firmware mod?

**Comment by MuntadherTY** [comment]
> Have you installed openwrt or the stock firmware mod?

openwrt

**Comment by MariosK239** [comment]
You can make a post on the openwrt forum: https://forum openwrt.org/ so as to get help faster. Also, if you have installed the openwrt version provided in this repository you might want to update to a newer snapshot image, but beware, snapshots dont normally come with a web interface, so you will only have access through ssh.

**Comment by MariosK239** [comment]
Since this is a github issue we should stop communicating here. My account on the openwrt forum is here: https://forum.openwrt.org/u/mariok239

**Comment by MuntadherTY** [comment]
> Since this is a github issue we should stop communicating here. My account on the openwrt forum is here: https://forum.openwrt.org/u/mariok239

do you have discord? because IDK how I would chat u there
![image](https://user-images.githubusercontent.com/79365018/126641033-2be6850a-92ed-4ca9-8556-d270bbf106f0.png)

**Comment by MariosK239** [comment]
My discord tag is: marios239#7607

**Comment by MariosK239** [comment]
@eisaev please close

**Comment by MuntadherTY** [comment]
> My discord tag is: marios239#7607

sent please accept fast cuz i ran into a problem i will cry the router is bootlooping
